language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-11

script:
  - export CC=gcc-11
  - export CXX=g++-11
  - cmake --version
  - cmake --preset unixlike-gcc-debug
  - cmake --build ./out/build/unixlike-gcc-debug/